### ISSUE TITLE
How to launch the GUI?

### ISSUE THREAD

**Issue by ShawnSun95** [sjtuyuxuan/sync_toolbox#1]
We have built the project but can not launch the GUI as "image/gui_1.png" shows. Maybe the file sync_toolbox_node.cpp is missing. Could you give us a tutorial on how to run this toolbox?

**Comment by sjtuyuxuan** [comment]
Hi 由于我在美国，可能有一些时差，我们能wx😊联系吗，来具体看一下是啥问题。 我的wx 是 liangyuxuanwx

**Comment by ShawnSun95** [comment]
谢谢，我加您
